Catch TypeError when comparing datetimes
See https://docs.sqlalchemy.org/en/13/changelog/migration_06.html#an-important-expression-language-gotcha
If we do something like:
Core10.when_created == latest_records.c.when_created in a query we end up in
coerce_to_pendulum(), which has the line:
if not x:
    return None

The base ClauseElement now raises an exception if called in a boolean context:
TypeError: Boolean value of this clause is not defined

The easiest thing to do is to add TypeError to the list of exceptions already
handled in the PendulumDateTimeAsIsoTextColType class